name: Release

on:
  push:
    branches:
      - main
      - next

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}         # Required for semantic-release auth
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}     # Used by Docker login + GH API
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npx tsc

      - name: Run semantic-release
        run: |
          export GITHUB_REPOSITORY=${{ github.repository }}
          export GITHUB_ACTOR=${{ github.actor }}
          npx semantic-release
